version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - checkout
      - run:
          command: bundle install
      - run:
          command: bundle exec rspec

workflows:
  setup:
    jobs:
      - setup
